import '../styles/style.sass'

import './includes/toggle'
import './includes/changeFooterYear'
import './includes/highlght'
import './includes/setActiveNavbarLink'
import './includes/jsCarousel'
import './includes/lazyLoad'
import './includes/sortByTag'
import './includes/routing'